MetaStudio/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('game.urls')),
    url(r'', include('comment.urls')),
    url(r'', include('account.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^api/', include('api.urls')),
]

api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns=[
    url(r'test/$', views.Test.as_view(), name='Test'),
   
]

blog/urls.py
from django.conf.urls import url
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
from . import views
from MetaStudio.settings import MEDIA_ROOT

app_name = "blog"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index.html$', views.index, name='index'),
    url(r'^about.html$', views.about, name='about'),
    url(r'^blog.html$', views.blog, name='blog'),
    url(r'^contact.html$', views.contact, name='contact'),
    url(r'^post/(?P<pk>[0-9]+)', views.detail, name='detail'),
    url(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    url(r'^write/', views.write, name='write'),
    url(r'^post/delete/(?P<pk>[0-9]+)', views.delete, name='delete'),
    url(r'^post/edit/(?P<pk>[0-9]+)', views.edit, name='edit'),
    # url(r'^upload', views.uploadImage, name="UploadImage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'game'

urlpatterns=[
    url(r'^portfolio.html$', views.portfllio, name='portfolio'),
    url(r'^game/(?P<pk>[0-9]+)', views.gameInfo, name='gameInfo'),
    url(r'^download/Game/(?P<pk>[0-9]+)', views.downloadGame, name='downloadGame'),
    url(r'^upload/Game/$', views.uploadGame, name='uploadGame'),
    url(r'^delete/Game/(?P<pk>[0-9]+)', views.deleteGame, name='deleteGame'),
    url(r'^edit/Game/(?P<pk>[0-9]+)', views.editGame, name='editGame'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from MetaStudio.settings import AUTH_USER_MODEL
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length = 100)
    createTime = models.DateTimeField(auto_now_add=True)
    modifiedTime = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    excerpt = models.CharField(max_length=200, blank = True)
    views = models.PositiveIntegerField(default=0)

    category = models.ForeignKey(Category)
    tag = models.ManyToManyField(Tag)

    author = models.ForeignKey(AUTH_USER_MODEL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs = { 'pk':self.pk })

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

comment/models.py
from django.db import models
from MetaStudio.settings import AUTH_USER_MODEL

# Create your models here.


class BlogComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey("blog.Post")
    user = models.ForeignKey("account.User")

    def __str__(self):
        return self.text[:20]


class SubBComment(models.Model):
    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    parentComment = models.ForeignKey("BlogComment")
    user = models.ForeignKey("account.User",related_name="user")
    toUser = models.ForeignKey("account.User", related_name="toUser")

    def __str__(self):
        return self.text[:20]


class GameComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    game = models.ForeignKey("game.Game")
    user = models.ForeignKey("account.User")

    def __str__(self):
        return self.text[:20]


class SubGComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    parentComment = models.ForeignKey("GameComment")
    user = models.ForeignKey("account.User", related_name="member")
    toUser = models.ForeignKey("account.User", related_name="toMember")

    def __str__(self):
        return self.text[:20]

game/models.py
from django.db import models
from django.urls import reverse
from account.models import User

class GameCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Game(models.Model):

    name = models.CharField(max_length=100)
    createTime = models.DateTimeField(auto_now_add=True)
    excrept = models.TextField(blank=True, max_length=300)
    times = models.PositiveIntegerField(default=0)
    icon = models.ImageField(default='default/icon.jpg')
    version = models.CharField(max_length=30)
    game = models.FileField()
    inTro = models.TextField(blank=True)
    foreImg = models.ImageField(default='default/foreImg.jpg')

    category = models.ForeignKey(GameCategory)
    author = models.ForeignKey(User)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('game:gameInfo', kwargs={'pk': self.pk})

    def increase_times(self):
        self.times += 1
        self.save(update_fields=['times'])

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','body','category','tag','author']

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Category, Tag, Post
from game.models import GameCategory, Game
from comment.forms import BlogCommentForm,SubBCommentForm
from comment.models import BlogComment,SubBComment
from .forms import PostForm

def index(request):
    posts = Post.objects.all().order_by("-createTime")[:5]
    games = Game.objects.all().order_by("-createTime")[:3]
    context = {
        'posts': posts,
        'games': games,
    }
    return render(request, 'home/index.html', context = context)

def blog(request):
    categories = Category.objects.all().order_by("name")
    postList = []
    for cate in categories:
        posts = Post.objects.filter(category=cate.pk).order_by("-createTime")
        temp = (cate,posts)
        postList.append(temp)
    context = {
        "categories": categories,
        "postList": postList,
    }
    return render(request, 'home/blog.html', context = context)

def about(request):
    return render(request, 'home/about.html', context = None)

def contact(request):
    return render(request, 'home/contact.html', context = None)

def detail(request,pk):

    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    form = BlogCommentForm()
    subForm = SubBCommentForm()
    c = post.blogcomment_set.all()
    comments = []

    for comment in c:
        subComment = SubBComment.objects.filter(parentComment=comment.pk).order_by("createTime")
        temp = (comment,subComment)
        comments.append(temp)

    context = {
        'post': post,
        'form': form,
        'subForm': subForm,
        'comments': comments,
    }

    return render(request, 'blog/detail.html', context=context)


def write(request):
    categories = Category.objects.all()
    tags = Tag.objects.all()

    if request.method == "POST":
        print(request.POST)
        form = PostForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = PostForm()

    return render(request, 'blog/write.html', context={'form': form, 'categories': categories, 'tags': tags})


def delete(request, pk):
    Post.objects.filter(pk=pk).delete()
    return redirect("/user/")


def edit(request, pk):
    categories = Category.objects.all()
    tags = Tag.objects.all()
    post=get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        content = request.POST
        print(content)
        post.title = content['title']
        post.category.pk = content['category']
        post.tag.pk = content['tag']
        post.body = content['body']
        post.save()
        return redirect("/user")

    context = {'post': post, 'categories': categories, 'tags': tags}

    return render(request, 'blog/edit.html', context=context)

templates/home/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    关于——META STUDIO
{% endblock title %}
{% block narAbout %}
    fh5co-active
{% endblock narAbout %}
    {% block body %}
		<div id="fh5co-main">
			<div class="fh5co-narrow-content">
				<div class="row row-bottom-padded-md">
					<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
						<img class="img-responsive" src="{% static 'images/img_bg_1.jpg' %}" alt="Free HTML5 Bootstrap Template by FreeHTML5.co">
					</div>
					<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
						<h2 class="fh5co-heading">关于工作室</h2>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Quisque sit amet efficitur nih. Interdum et malesuada fames ac ante ipsum primis in faucibus interda et malesuada parturient.</p>
						<p>Quisque sit amet efficitur nih. Interdum et malesuada fames ac ante ipsum primis in faucibus interda et malesuada parturient.</p>
					</div>
				</div>
			</div>

			<div class="fh5co-narrow-content">
					<h2 class="fh5co-heading animate-box" data-animate-effect="fadeInLeft">Our Services</h2>
					<div class="row">
						<div class="col-md-6">
							<div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
								<div class="fh5co-icon">
									<i class="icon-settings"></i>
								</div>
								<div class="fh5co-text">
									<h3>Strategy</h3>
									<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
								<div class="fh5co-icon">
									<i class="icon-search4"></i>
								</div>
								<div class="fh5co-text">
									<h3>Explore</h3>
									<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
								</div>
							</div>
						</div>

						<div class="col-md-6">
							<div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
								<div class="fh5co-icon">
									<i class="icon-paperplane"></i>
								</div>
								<div class="fh5co-text">
									<h3>Direction</h3>
									<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
								<div class="fh5co-icon">
									<i class="icon-params"></i>
								</div>
								<div class="fh5co-text">
									<h3>Expertise</h3>
									<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
								</div>
							</div>
						</div>
					</div>
				</div>
		
			<div class="fh5co-narrow-content">
				<div class="row">
					<div class="col-md-4 animate-box" data-animate-effect="fadeInLeft">
						<h1 class="fh5co-heading-colored">联系我们</h1>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
						<p class="fh5co-lead">Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
						<p><a href="{% url 'blog:contact'%}#contact" class="btn btn-primary">Learn More</a></p>
					</div>
					
				</div>
			</div>
		</div>
    {% endblock body %}

templates/home/blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    博客——META STUDIO
{% endblock title %}
{% block narBlog %}
    fh5co-active
{% endblock narBlog %}
    {% block body %}
		<div id="fh5co-main">
			<div class="fh5co-narrow-content">
                <a class="btn btn-primary pull-right" href="{% url 'blog:write' %}">写博客</a>
                {% for cate,posts in postList %}
                {% if cate.post_set.count %}
				<h2 class="fh5co-heading animate-box" data-animate-effect="fadeInLeft">{{ cate.name }}<small class="badge">{{ cate.post_set.count }}</small></h2>
				<div class="row row-bottom-padded-md">
                    {% for post in posts %}
					<div class="col-padding animate-box" data-animate-effect="fadeInLeft">
						<div class="blog-entry">
							<div class="desc">
								<h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
								<span><small>by {{ post.author }} </small> / <small> {{ post.category }} </small> / <small> <i class="glyphicong lyphicon-comment"></i> 评论{{ post.blogcomment_set.count }}</small> / <small>阅读{{ post.views }}</small>&nbsp;&nbsp;<small>{{ post.createTime }}</small></span>
								<p>{{ post.body|truncatechars:54}}</p>
								<a href="{{ post.get_absolute_url }}" class="lead pull-right">阅读全文 <i class="icon-arrow-right3"></i></a>
							</div>
						</div>
					</div>
                    {% endfor %}
                </div>
                {% endif %}
                {% empty %}
                    暂无博客
                {% endfor %}
			</div>
		</div>
    {% endblock body %}

templates/home/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    联系——META STUDIO
{% endblock title %}
{% block narContact %}
    fh5co-active
{% endblock narContact %}
    {% block body %}
		<div id="fh5co-main">
			<div class="fh5co-more-contact">
				<div class="fh5co-narrow-content">
					<div class="row">
						<div class="col-md-4">
							<div class="fh5co-feature fh5co-feature-sm animate-box" data-animate-effect="fadeInLeft">
								<div class="fh5co-icon">
									<i class="icon-globe"></i>
								</div>
								<div class="fh5co-text">
									<p><a href="#">info@domain.com</a></p>
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="fh5co-feature fh5co-feature-sm animate-box" data-animate-effect="fadeInLeft">
								<div class="fh5co-icon">
									<i class="icon-map"></i>
								</div>
								<div class="fh5co-text">
									<p>198 West 21th Street, Suite 721 New York NY 10016</p>
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="fh5co-feature fh5co-feature-sm animate-box" data-animate-effect="fadeInLeft">
								<div class="fh5co-icon">
									<i class="icon-phone"></i>
								</div>
								<div class="fh5co-text">
									<p><a href="tel://">+123 456 7890</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="fh5co-narrow-content animate-box" data-animate-effect="fadeInLeft" id="contact">
				
				<div class="row">
					<div class="col-md-4">
						<h2>联系我们</h2>
					</div>
				</div>
				<form action="">
					<div class="row">
						<div class="col-md-12">
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<input type="text" class="form-control" placeholder="姓名">
									</div>
									<div class="form-group">
										<input type="text" class="form-control" placeholder="邮件">
									</div>
									<div class="form-group">
										<input type="text" class="form-control" placeholder="电话">
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<textarea name="" id="message" cols="30" rows="7" class="form-control" placeholder="请输入"></textarea>
									</div>
									<div class="form-group">
										<input type="submit" class="btn btn-primary btn-md" value="发送">
									</div>
								</div>
								
							</div>
						</div>
					</div>
				</form>
			</div>
			<div id="map"></div>	
		</div>
    {% endblock body %}

templates/home/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    首页——META STUDIO
{% endblock title %}
{% block narHome %}
    fh5co-active
{% endblock narHome %}
{% block body %}
		<div id="fh5co-main">
			<aside id="fh5co-hero" class="js-fullheight">
				<div class="flexslider js-fullheight">
					<ul class="slides">
                    {% for game in games %}
				   	<li style="background-image: url({{ game.foreImg.url }});">
				   		<div class="overlay"></div>
				   		<div class="container-fluid">
				   			<div class="row">
					   			<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
					   				<div class="slider-text-inner">
					   					<h1>{{ game.name }}</h1>
					   					<h2>{{ game.excrept }}</h2>
                                        <p>
                                            <a class="btn btn-primary btn-demo popup-vimeo" href="{% url 'game:downloadGame' game.pk %}" title="点击下载">
                                                <i class="icon-arrow-down3"></i>
                                                点击下载
                                            </a>
                                            <a class="btn btn-primary btn-learn" href="{{ game.get_absolute_url }}" title="了解更多">
                                                了解更多<i class="icon-arrow-right3"></i>
                                            </a>
                                        </p>
					   				</div>
					   			</div>
					   		</div>
				   		</div>
				   	</li>
                    {% empty %}
                        暂无游戏
                    {% endfor %}
				  	</ul>
			  	</div>
			</aside>

			<div class="fh5co-narrow-content">
				<h2 class="fh5co-heading animate-box" data-animate-effect="fadeInLeft">最新博客</h2>
				<div class="row row-bottom-padded-md">
                    {% for post in posts %}
					<div class="col-padding animate-box" data-animate-effect="fadeInLeft">
						<div class="blog-entry">
							<div class="desc">
								<h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
								<span><small>by {{ post.author }} </small> / <small> {{ post.category }} </small> / <small> <i class="icon-comment"></i> 评论{{ post.blogcomment_set.count }}</small> / <small>阅读{{ post.views }}</small>&nbsp;&nbsp;<small>{{ post.createTime }}</small></span>
								<p>{{ post.body|truncatechars:54 }}</p>
								<a href="{{ post.get_absolute_url }}" class="lead pull-right">阅读全文 <i class="icon-arrow-right3"></i></a>
							</div>
						</div>
					</div>
                    {% empty %}
                    暂无博客
                    {% endfor %}
				</div>
			</div>
		</div>
{% endblock body %}
    

templates/home/portfolio.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Game——META STUDIO
{% endblock title %}
{% block narGame %}
    fh5co-active
{% endblock narGame %}
    {% block body %}
		<div id="fh5co-main">
			<div class="fh5co-narrow-content">
                <a class="btn btn-primary pull-right" href="{% url 'game:uploadGame' %}">上传游戏</a>
                {% for cate,games in gameList %}
				<h2 class="fh5co-heading animate-box" data-animate-effect="fadeInLeft">{{ cate.name }}<small class="badge">{{ cate.game_set.count }}</small></h2>
				<div class="row row-bottom-padded-md">
                    {% for game in games %}
					<div class="col-md-3 col-sm-6 col-padding text-center animate-box">
						<a href="{{ game.get_absolute_url }}" class="work image-popup" style="background-image: url({{ game.foreImg.url }});">
							<div class="desc">
                                <h3>{{ game.name }}</h3>
								<span>{{ game.times }} 下载</span>
							</div>
						</a>
					</div>
                    {% empty %}
                        该目录下暂无游戏，敬请期待
                    {% endfor %}
				</div>
                {% empty %}
                    暂无游戏目录，敬请期待
                {% endfor %}
			</div>
		</div>
    {% endblock body %}