MetaStudio/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('game.urls')),
    url(r'', include('comment.urls')),
    url(r'', include('account.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^api/', include('api.urls')),
]

account/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'account'

urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user/$',views.userInfo, name="userInfo"),
    url(r'^userInfo/$', views.infoChange, name='infoChange'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns=[
    url(r'test/$', views.Test.as_view(), name='Test'),
   
]

comment/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "comment"

urlpatterns=[
    url(r'comment/post/(?P<post_pk>[0-9]+)$', views.post_comment, name='post_comment'),
    url(r'comment/game/(?P<game_pk>[0-9]+)$', views.game_comment, name='game_comment'),
    url(r'subComment/post/(?P<post_pk>[0-9]+)/(?P<comment_pk>[0-9]+)$', views.sub_post_comment, name="sub_post_comment"),
    url(r'subComment/game/(?P<game_pk>[0-9]+)/(?P<comment_pk>[0-9]+)$', views.sub_game_comment, name="sub_game_comment"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'game'

urlpatterns=[
    url(r'^portfolio.html$', views.portfllio, name='portfolio'),
    url(r'^game/(?P<pk>[0-9]+)', views.gameInfo, name='gameInfo'),
    url(r'^download/Game/(?P<pk>[0-9]+)', views.downloadGame, name='downloadGame'),
    url(r'^upload/Game/$', views.uploadGame, name='uploadGame'),
    url(r'^delete/Game/(?P<pk>[0-9]+)', views.deleteGame, name='deleteGame'),
    url(r'^edit/Game/(?P<pk>[0-9]+)', views.editGame, name='editGame'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/models.py
from django.db import models
from MetaStudio.settings import AUTH_USER_MODEL

# Create your models here.


class BlogComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey("blog.Post")
    user = models.ForeignKey("account.User")

    def __str__(self):
        return self.text[:20]


class SubBComment(models.Model):
    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    parentComment = models.ForeignKey("BlogComment")
    user = models.ForeignKey("account.User",related_name="user")
    toUser = models.ForeignKey("account.User", related_name="toUser")

    def __str__(self):
        return self.text[:20]


class GameComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    game = models.ForeignKey("game.Game")
    user = models.ForeignKey("account.User")

    def __str__(self):
        return self.text[:20]


class SubGComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    parentComment = models.ForeignKey("GameComment")
    user = models.ForeignKey("account.User", related_name="member")
    toUser = models.ForeignKey("account.User", related_name="toMember")

    def __str__(self):
        return self.text[:20]

game/models.py
from django.db import models
from django.urls import reverse
from account.models import User

class GameCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Game(models.Model):

    name = models.CharField(max_length=100)
    createTime = models.DateTimeField(auto_now_add=True)
    excrept = models.TextField(blank=True, max_length=300)
    times = models.PositiveIntegerField(default=0)
    icon = models.ImageField(default='default/icon.jpg')
    version = models.CharField(max_length=30)
    game = models.FileField()
    inTro = models.TextField(blank=True)
    foreImg = models.ImageField(default='default/foreImg.jpg')

    category = models.ForeignKey(GameCategory)
    author = models.ForeignKey(User)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('game:gameInfo', kwargs={'pk': self.pk})

    def increase_times(self):
        self.times += 1
        self.save(update_fields=['times'])

game/forms.py
from django import forms
from .models import Game, GameCategory

class UploadGameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'version', 'inTro', 'category', 'author']

game/views.py
import os

from django.shortcuts import render,get_object_or_404, redirect
from django.http import FileResponse

from .models import GameCategory, Game
from comment.forms import GameCommentForm,SubGCommentForm
from comment.models import SubGComment
from .forms import UploadGameForm

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def portfllio(request):
    categories = GameCategory.objects.all().order_by("name")
    gameList = []
    for cate in categories:
        games = Game.objects.filter(category = cate.pk).order_by("-createTime")
        temp = (cate,games)
        gameList.append(temp)

    return render(request, 'home/portfolio.html', context={'gameList': gameList})


def gameInfo(request,pk):
    game = get_object_or_404(Game, pk=pk)
    form = GameCommentForm()
    subForm = SubGCommentForm()
    c = game.gamecomment_set.all()
    comments = []
    for comment in c:
        subComment = SubGComment.objects.filter(parentComment=comment.pk).order_by("createTime")
        temp = (comment,subComment)
        comments.append(temp)

    context = {
        'game': game,
        'form': form,
        'subForm': subForm,
        'comments': comments,
    }
    return render(request, 'game/game.html', context=context)

def downloadGame(request, pk):
    gameObj = get_object_or_404(Game, pk=pk)
    url = BASE_DIR+str(gameObj.game.url).replace('/', '\\')
    name = str(gameObj.game)
    file = open(url, 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{0}"'.format(name)

    gameObj.increase_times()
    return response

def uploadGame(request):
    categories = GameCategory.objects.all()

    if request.method == 'POST':
        form = UploadGameForm(request.POST)
        gamelication = request.FILES['game']

        if form.is_valid():
            game = form.save(commit=False)
            game.game = gamelication
            if 'icon' not in request.POST:
                game.icon = request.FILES['icon']
            if 'foreImg' not in request.POST:
                game.foreImg = request.FILES['foreImg']
            game.save()
            return redirect('/')
    else:
        form = UploadGameForm()
    return render(request, 'game/upload.html', context={'form': form, 'categories': categories})

def deleteGame(request, pk):
    Game.objects.filter(pk=pk).delete()
    return redirect("/user/")

def editGame(request, pk):
    categories = GameCategory.objects.all()
    game = get_object_or_404(Game, pk=pk)

    if request.method == 'POST':
        content = request.POST
        game.name = content['name']
        game.version = content['version']
        game.category.pk = content['category']
        game.inTro = content['inTro']
        if 'icon' not in request.POST:
            game.icon = request.FILES['icon']
        if 'foreImg' not in request.POST:
            game.foreImg = request.FILES['foreImg']
        if 'game' not in request.POST:
            game.game = request.FILES['game']
        game.save()
        return redirect("/user/")
    context = {'categories': categories,'game': game}

    return render(request, 'game/edit.html',context=context)

templates/game/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    修改游戏——META STUDIO
{% endblock title %}
{% block body %}
		<div id="fh5co-main">
			<div class="fh5co-narrow-content">
                <div class="panel panel-default">
                    <div class="panel-heading">游戏上传</div>
                    <div class="panel-body">
                        <form class="form" action="{% url 'game:editGame' game.pk %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <div class="form-group">
                                <label for="title" class="sr-only">游戏名称(必填)</label>
                                <input type="text" name="name" id="title" value="{{ game.name }}" placeholder="游戏名称(必填)" class="form-control" maxlength="100" required>
                                {{ form.title.errors }}
                                {% if form.title.help_text %}
                                    {{ form.title.help_text|safe }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="version" class="sr-only">游戏版本(必填)</label>
                                <input type="text" name="version" id="version" value="{{ game.version }}" placeholder="版本(必填)" class="form-control" maxlength="100" required>
                                {{ form.title.errors }}
                                {% if form.title.help_text %}
                                    {{ form.title.help_text|safe }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="category" class="">游戏分类(必填)</label>
                                <select class="" id="category" name="category" required>
                                  {% for cate in categories %}
                                      <option value="{{ cate.pk }}">{{ cate.name }}</option>
                                  {% endfor %}
                                </select>
                                {{ form.category.errors }}
                                {% if form.category.help_text %}
                                    {{ form.category.help_text|safe }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="body" class="sr-only"></label>
                                <input  name="inTro" id="body" value="{{ game.inTro }}" class="form-control" placeholder="简介(必填)" required/>
                                {{ form.inTro.errors }}
                                {% if form.inTro.help_text %}
                                    {{ form.inTro.help_text|safe }}
                                {% endif %}
                            </div>
                            <input type="hidden" value="{{ user.pk }}" name="author">
                            <div class="form-group">
                                <label for="game">游戏(必填)&nbsp;&nbsp;</label>
                                <span class="h4">目前：{{ game.game }}</span>
                                <input type="file" name="game" id="game"/>
                            </div>
                            <div class="form-group">
                                <label for="icon" class="">游戏图标&nbsp;&nbsp;</label>
                                <span class="h4">目前：{{ game.icon }}</span>
                                <input type="file" name="icon" id="icon" value="{{ game.icon }}"/>
                                <label for="foreImg" class="">游戏展示图片&nbsp;&nbsp;</label>
                                <span class="h4">目前：{{ game.foreImg }}</span>
                                <input type="file" name="foreImg" id="foreImg" value="{{ game.foreImg }}"/>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-default form-control">确认修改</button>
                            </div>
                        </form>
                    </div>
                </div>
			</div>
		</div>
{% endblock body %}

templates/game/game.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    游戏详情——META STUDIO
{% endblock title %}
    {% block body %}
		<div id="fh5co-main">
			<div class="fh5co-narrow-content">
                <div class="panel panel-default">
                    <div class="panel-heading">游戏介绍</div>
                    <div class="panel-body row">
                        <div class="col-md-3">
                            <img class="img-rounded" src="{{ game.icon.url }}" width="200" height="200">
                            <br>
                            <br>
                            <a class="btn btn-primary btn-learn" href="{{ game.game.url }}" title="点击下载">
                                <i class="icon-arrow-down3"></i>
                                DownLoad
                            </a>
                        </div>
                        <div class="col-md-9">
                            <h3>{{ game.name }}</h3>
                            <div class="row">
                                <table class="table table-striped">
                                <tr>
                                    <td>游戏名称: </td>
                                    <td>{{ game.name }}</td>
                                    <td>分类: </td>
                                    <td>{{ game.category }}</td>
                                </tr>
                                <tr>
                                    <td>发行版本: </td>
                                    <td>{{ game.version }}</td>
                                    <td>发布时间:</td>
                                    <td>{{ game.createTime.year }}年{{ game.createTime.month}}月{{ game.createTime.day }}日</td>
                                </tr>
                                <tr>
                                    <td>大小：</td>
                                    <td>{{ game.game.size }}字节</td>
                                    <td>下载量: </td>
                                    <td>{{ game.times }} 次</td>
                                </tr>
                            </table>
                            <span>{{ game.excrept }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">游戏详情</div>
                    <div class="panel-body">
{#                        <video controls class="center-block" width="600" height="300">#}
{#                            <source src="{{ MEDIA_URL }}{{ app.video }}">#}
{#                            ungrade your browser to support this!#}
{#                        </video>#}
{#                        <hr>#}
                        <p>
                            {{ game.inTro }}
                        </p>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">发表评论</div>
                    <div class="panel-body">
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'comment:game_comment' game.pk %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 col-sm-12 form-group">
                                    <label for="text" class="sr-only">请输入</label>
                                    <textarea placeholder="请输入" name="text" id="text" rows="4" class="form-control"></textarea>
                                    {{ form.text.errors }}
                                </div>
                                <div class="col-md-12 col-sm-12 form-group">
                                    <input  type="submit" value="发送" class="form-control btn btn-default">
                                </div>
                            </div>
                        </form>
                        {% else %}
                            <p class="text-center">
                                <a href="{% url 'account:login' %}?next={{ request.path }}">登陆</a>/
                                <a href="{% url 'account:register' %}?next={{ request.path }}">注册</a>后评论
                            </p>
                        {% endif %}
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">游戏评价<small class="badge">{{ game.gamecomment_set.count }}</small></div>
                    <div class="panel-body">
                        <ul class="media-list">
                            {% for comment,subComment in comments %}
                            <li class="media">
                                <div class="media-left">
                                  <a href="#">
                                    <img class="media-object img-rounded" src="{{ comment.user.headphoto.url }}" width="50" height="50">
                                  </a>
                                </div>
                                <div class="media-body">
                                    <span class="media-heading h4">{{ comment.user }}</span>
                                    <time>{{ comment.createTime }}</time>
                                    <p>
                                        {{ comment.text }}
                                        <button data-toggle="collapse" data-target="#comment{{ comment.pk }}" class="pull-right"
                                                aria-expanded="false" aria-controls="comment{{ comment.pk }}">回复</button>
                                    </p>
                                    <div>
                                        <div class="collapse" id="comment{{ comment.pk }}">
                                          <div class="well">
                                              <form method="post" action="{% url 'comment:sub_game_comment' game.pk comment.pk%}">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <div class="col-md-12 col-sm-12 form-group">
                                                        <label for="Text{{ comment.pk }}" class="sr-only">请输入</label>
                                                        <textarea placeholder="请输入" name="text" id="Text{{ comment.pk }}" class="form-control"></textarea>
                                                        {{ subForm.text.errors }}
                                                    </div>
                                                    <div class="col-md-12 col-sm-12 form-group">
                                                        <label for="User{{ comment.pk }}" class="sr-only">User</label>
                                                        <input type="hidden" name="user" id="User{{ comment.pk }}" class="form-control" value="{{ user.pk }}">
                                                        {{ subForm.user.errors }}
                                                    </div>
                                                    <div class="col-md-12 col-sm-12 form-group">
                                                        <label for="ToUser{{ comment.pk }}" class="sr-only">toUser</label>
                                                        <input type="hidden" name="toUser" id="ToUser{{ comment.pk }}" class="form-control" value="{{ comment.user.pk }}">
                                                        {{ subForm.toUser.errors }}
                                                    </div>
                                                    <div class="col-md-12 col-sm-12 form-group">
                                                        <input  type="submit" value="发送" class="pull-right btn btn-default">
                                                    </div>
                                                </div>
                                            </form>
                                          </div>
                                        </div>
                                    </div>
                                    <ul class="media-list">
                                        {% for sub in subComment %}
                                        <li class="media">
                                            <div class="media-left">
                                              <a href="#">
                                                <img class="media-object img-rounded" src="{{ sub.user.headphoto.url }}" width="40" height="40">
                                              </a>
                                            </div>
                                            <div class="media-body">
                                                <span class="media-heading h4">{{ sub.user }}回复{{ sub.toUser }}</span>
                                                <time>{{ sub.createTime }}</time>
                                                <p>
                                                    {{ sub.text }}
                                                    <button data-toggle="collapse" data-target="#collapse{{ sub.pk }}" class="pull-right"
                                                                    aria-expanded="false" aria-controls="collapse{{ sub.pk }}">回复</button>
                                                </p>
                                                <div>
                                                    <div class="collapse" id="collapse{{ sub.pk }}">
                                                      <div class="well">
                                                          <form method="post" action="{% url 'comment:sub_game_comment' game.pk comment.pk %}">
                                                            {% csrf_token %}
                                                            <div class="row">
                                                                <div class="col-md-12 col-sm-12 form-group">
                                                                    <label for="text{{ sub.pk }}" class="sr-only">请输入</label>
                                                                    <textarea placeholder="请输入" name="text" id="text{{ sub.pk }}" class="form-control"></textarea>
                                                                    {{ subForm.text.errors }}
                                                                </div>
                                                                <div class="col-md-12 col-sm-12 form-group">
                                                                    <label for="user{{ sub.pk }}" class="sr-only">User</label>
                                                                    <input type="hidden" name="user" id="user{{ sub.pk }}" class="form-control" value="{{ user.pk }}">
                                                                </div>
                                                                <div class="col-md-12 col-sm-12 form-group">
                                                                    <label for="toUser{{ sub.pk }}" class="sr-only">ToUser</label>
                                                                    <input type="hidden" name="toUser" id="toUser{{ sub.pk }}" class="form-control" value="{{ sub.parentComment.user.pk }}">
                                                                </div>
                                                                <div class="col-md-12 col-sm-12 form-group">
                                                                    <input  type="submit" value="发送" class="btn btn-default pull-right">
                                                                </div>
                                                            </div>
                                                          </form>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                            {% empty %}
                                暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </div>
			</div>
		</div>
    {% endblock body %}

templates/game/upload.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    上传游戏——META STUDIO
{% endblock title %}
{% block body %}
		<div id="fh5co-main">
			<div class="fh5co-narrow-content">
                <div class="panel panel-default">
                    <div class="panel-heading">游戏上传</div>
                    <div class="panel-body">
                        <form class="form" action="{% url 'game:uploadGame' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <div class="form-group">
                                <label for="title" class="sr-only">游戏名称(必填)</label>
                                <input type="text" name="name" id="title" placeholder="游戏名称(必填)" class="form-control" maxlength="100" required>
                                {{ form.title.errors }}
                                {% if form.title.help_text %}
                                    {{ form.title.help_text|safe }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="version" class="sr-only">游戏版本(必填)</label>
                                <input type="text" name="version" id="version" placeholder="游戏版本(必填)" class="form-control" maxlength="100" required>
                                {{ form.title.errors }}
                                {% if form.title.help_text %}
                                    {{ form.title.help_text|safe }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="category" class="">游戏分类(必填)</label>
                                <select class="" id="category" name="category" required>
                                  {% for cate in categories %}
                                      <option value="{{ cate.pk }}">{{ cate.name }}</option>
                                  {% endfor %}
                                </select>
                                {{ form.category.errors }}
                                {% if form.category.help_text %}
                                    {{ form.category.help_text|safe }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                <label for="body" class="sr-only"></label>
                                <input  name="inTro" id="body" class="form-control" placeholder="游戏简介(必填)" required/>
                                {{ form.inTro.errors }}
                                {% if form.inTro.help_text %}
                                    {{ form.inTro.help_text|safe }}
                                {% endif %}
                            </div>
                            <input type="hidden" value="{{ user.pk }}" name="author">
                            <div class="form-group">
                                <label for="game">游戏(必填)</label>
                                <input type="file" name="game" id="game" required/>
                            </div>
                            <div class="form-group">
                                <label for="icon" class="">游戏图标</label>
                                <input type="file" name="icon" id="icon"/>
                                <label for="foreImg" class="">游戏展示图片</label>
                                <input type="file" name="foreImg" id="foreImg"/>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-default form-control">上传游戏</button>
                            </div>
                        </form>
                    </div>
                </div>
			</div>
		</div>
{% endblock body %}