MetaStudio/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('game.urls')),
    url(r'', include('comment.urls')),
    url(r'', include('account.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^api/', include('api.urls')),
]

account/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'account'

urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user/$',views.userInfo, name="userInfo"),
    url(r'^userInfo/$', views.infoChange, name='infoChange'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns=[
    url(r'test/$', views.Test.as_view(), name='Test'),
   
]

blog/urls.py
from django.conf.urls import url
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
from . import views
from MetaStudio.settings import MEDIA_ROOT

app_name = "blog"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index.html$', views.index, name='index'),
    url(r'^about.html$', views.about, name='about'),
    url(r'^blog.html$', views.blog, name='blog'),
    url(r'^contact.html$', views.contact, name='contact'),
    url(r'^post/(?P<pk>[0-9]+)', views.detail, name='detail'),
    url(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    url(r'^write/', views.write, name='write'),
    url(r'^post/delete/(?P<pk>[0-9]+)', views.delete, name='delete'),
    url(r'^post/edit/(?P<pk>[0-9]+)', views.edit, name='edit'),
    # url(r'^upload', views.uploadImage, name="UploadImage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "comment"

urlpatterns=[
    url(r'comment/post/(?P<post_pk>[0-9]+)$', views.post_comment, name='post_comment'),
    url(r'comment/game/(?P<game_pk>[0-9]+)$', views.game_comment, name='game_comment'),
    url(r'subComment/post/(?P<post_pk>[0-9]+)/(?P<comment_pk>[0-9]+)$', views.sub_post_comment, name="sub_post_comment"),
    url(r'subComment/game/(?P<game_pk>[0-9]+)/(?P<comment_pk>[0-9]+)$', views.sub_game_comment, name="sub_game_comment"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from MetaStudio.settings import AUTH_USER_MODEL
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length = 100)
    createTime = models.DateTimeField(auto_now_add=True)
    modifiedTime = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    excerpt = models.CharField(max_length=200, blank = True)
    views = models.PositiveIntegerField(default=0)

    category = models.ForeignKey(Category)
    tag = models.ManyToManyField(Tag)

    author = models.ForeignKey(AUTH_USER_MODEL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs = { 'pk':self.pk })

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

comment/models.py
from django.db import models
from MetaStudio.settings import AUTH_USER_MODEL

# Create your models here.


class BlogComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey("blog.Post")
    user = models.ForeignKey("account.User")

    def __str__(self):
        return self.text[:20]


class SubBComment(models.Model):
    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    parentComment = models.ForeignKey("BlogComment")
    user = models.ForeignKey("account.User",related_name="user")
    toUser = models.ForeignKey("account.User", related_name="toUser")

    def __str__(self):
        return self.text[:20]


class GameComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    game = models.ForeignKey("game.Game")
    user = models.ForeignKey("account.User")

    def __str__(self):
        return self.text[:20]


class SubGComment(models.Model):

    text = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    parentComment = models.ForeignKey("GameComment")
    user = models.ForeignKey("account.User", related_name="member")
    toUser = models.ForeignKey("account.User", related_name="toMember")

    def __str__(self):
        return self.text[:20]

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','body','category','tag','author']

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Category, Tag, Post
from game.models import GameCategory, Game
from comment.forms import BlogCommentForm,SubBCommentForm
from comment.models import BlogComment,SubBComment
from .forms import PostForm

def index(request):
    posts = Post.objects.all().order_by("-createTime")[:5]
    games = Game.objects.all().order_by("-createTime")[:3]
    context = {
        'posts': posts,
        'games': games,
    }
    return render(request, 'home/index.html', context = context)

def blog(request):
    categories = Category.objects.all().order_by("name")
    postList = []
    for cate in categories:
        posts = Post.objects.filter(category=cate.pk).order_by("-createTime")
        temp = (cate,posts)
        postList.append(temp)
    context = {
        "categories": categories,
        "postList": postList,
    }
    return render(request, 'home/blog.html', context = context)

def about(request):
    return render(request, 'home/about.html', context = None)

def contact(request):
    return render(request, 'home/contact.html', context = None)

def detail(request,pk):

    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    form = BlogCommentForm()
    subForm = SubBCommentForm()
    c = post.blogcomment_set.all()
    comments = []

    for comment in c:
        subComment = SubBComment.objects.filter(parentComment=comment.pk).order_by("createTime")
        temp = (comment,subComment)
        comments.append(temp)

    context = {
        'post': post,
        'form': form,
        'subForm': subForm,
        'comments': comments,
    }

    return render(request, 'blog/detail.html', context=context)


def write(request):
    categories = Category.objects.all()
    tags = Tag.objects.all()

    if request.method == "POST":
        print(request.POST)
        form = PostForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = PostForm()

    return render(request, 'blog/write.html', context={'form': form, 'categories': categories, 'tags': tags})


def delete(request, pk):
    Post.objects.filter(pk=pk).delete()
    return redirect("/user/")


def edit(request, pk):
    categories = Category.objects.all()
    tags = Tag.objects.all()
    post=get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        content = request.POST
        print(content)
        post.title = content['title']
        post.category.pk = content['category']
        post.tag.pk = content['tag']
        post.body = content['body']
        post.save()
        return redirect("/user")

    context = {'post': post, 'categories': categories, 'tags': tags}

    return render(request, 'blog/edit.html', context=context)

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    博客详情——META STUDIO
{% endblock title %}
    {% block body %}
		<div id="fh5co-main">
			<div class="fh5co-narrow-content">
{#				<h2 class="fh5co-heading animate-box" data-animate-effect="fadeInLeft">Recent blog</h2>#}
				<div class="row row-bottom-padded-md">
                    <div class="col-md-12 col-sm-12 col-padding animate-box" data-animate-effect="fadeInLeft">
						<div class="blog-entry">
							<div class="desc">
								<h3>{{ post.title }}</h3>
								<span><small>by {{ post.author }} </small> / <small> {{ post.category }} </small> / <small> <i class="icon-comment"></i> 评论{{ post.blogcomment_set.count }}</small> / <small>阅读{{ post.views }}</small>&nbsp;&nbsp;<small>{{ post.createTime }}</small></span>
								<p>{{ post.body|safe }}</p>
							</div>
						</div>
					</div>
				</div>
                <div class="panel panel-default">
                    <div class="panel-heading">发表评论</div>
                    <div class="panel-body">
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'comment:post_comment' post.pk %}">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12 col-sm-12 form-group">
                                        <label for="text" class="sr-only">请输入</label>
                                        <textarea placeholder="请输入" name="text" id="text" rows="4" class="form-control"></textarea>
                                        {{ form.text.errors }}
                                    </div>
                                    <div class="col-md-12 col-sm-12 form-group">
                                        <input  type="submit" value="发送" class="form-control btn btn-default">
                                    </div>
                                </div>
                            </form>
                        {% else %}
                            <p class="text-center">
                                <a href="{% url 'account:login' %}?next={{ request.path }}">登陆</a>/
                                <a href="{% url 'account:register' %}?next={{ request.path }}">注册</a>后评论
                            </p>
                        {% endif %}
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">评论列表<small class="badge">{{ post.blogcomment_set.count }}</small></div>
                    <div class="panel-body">
                        <ul class="media-list">
                            {% for comment,subComment in comments %}
                            <li class="media">
                                <div class="media-left">
                                  <a href="#">
                                    <img class="media-object img-rounded" src="{{ comment.user.headphoto.url }}" width="50" height="50" alt="...">
                                  </a>
                                </div>
                                <div class="media-body">
                                    <span class="media-heading h4">{{ comment.user }}</span>
                                    <time>{{ comment.createTime }}</time>
                                    <p>
                                        {{ comment.text }}
                                        <button data-toggle="collapse" data-target="#comment{{ comment.pk }}" class="pull-right"
                                                aria-expanded="false" aria-controls="comment{{ comment.pk }}">回复</button>
                                    </p>
                                    <div>
                                        <div class="collapse" id="comment{{ comment.pk }}">
                                          <div class="well">
                                              <form method="post" action="{% url 'comment:sub_post_comment' post.pk comment.pk%}">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <div class="col-md-12 col-sm-12 form-group">
                                                        <label for="Text{{ comment.pk }}" class="sr-only">请输入</label>
                                                        <textarea placeholder="请输入" name="text" id="Text{{ comment.pk }}" class="form-control"></textarea>
                                                        {{ subForm.text.errors }}
                                                    </div>
                                                    <div class="col-md-12 col-sm-12 form-group">
                                                        <label for="User{{ comment.pk }}" class="sr-only">User</label>
                                                        <input type="hidden" name="user" id="User{{ comment.pk }}" class="form-control" value="{{ user.pk }}">
                                                        {{ subForm.user.errors }}
                                                    </div>
                                                    <div class="col-md-12 col-sm-12 form-group">
                                                        <label for="ToUser{{ comment.pk }}" class="sr-only">toUser</label>
                                                        <input type="hidden" name="toUser" id="ToUser{{ comment.pk }}" class="form-control" value="{{ comment.user.pk }}">
                                                        {{ subForm.toUser.errors }}
                                                    </div>
                                                    <div class="col-md-12 col-sm-12 form-group">
                                                        <input  type="submit" value="发送" class="pull-right btn btn-default">
                                                    </div>
                                                </div>
                                            </form>
                                          </div>
                                        </div>
                                    </div>
                                    <ul class="media-list">
                                        {% for sub in subComment %}
                                        <li class="media">
                                            <div class="media-left">
                                              <a href="#">
                                                <img class="media-object img-rounded" src="{{ sub.user.headphoto.url }}" width="40" height="40">
                                              </a>
                                            </div>
                                            <div class="media-body">
                                                <span class="media-heading h4">{{ sub.user }}回复{{ sub.toUser }}</span>
                                                <time>{{ sub.createTime }}</time>
                                                <p>
                                                    {{ sub.text }}
                                                    <button data-toggle="collapse" data-target="#collapse{{ sub.pk }}" class="pull-right"
                                                                    aria-expanded="false" aria-controls="collapse{{ sub.pk }}">回复</button>
                                                </p>
                                                <div>
                                                    <div class="collapse" id="collapse{{ sub.pk }}">
                                                      <div class="well">
                                                          <form method="post" action="{% url 'comment:sub_post_comment' post.pk comment.pk %}">
                                                            {% csrf_token %}
                                                            <div class="row">
                                                                <div class="col-md-12 col-sm-12 form-group">
                                                                    <label for="text{{ sub.pk }}" class="sr-only">请输入</label>
                                                                    <textarea placeholder="请输入" name="text" id="text{{ sub.pk }}" class="form-control"></textarea>
                                                                    {{ subForm.text.errors }}
                                                                </div>
                                                                <div class="col-md-12 col-sm-12 form-group">
                                                                    <label for="user{{ sub.pk }}" class="sr-only">User</label>
                                                                    <input type="hidden" name="user" id="user{{ sub.pk }}" class="form-control" value="{{ user.pk }}">
                                                                </div>
                                                                <div class="col-md-12 col-sm-12 form-group">
                                                                    <label for="toUser{{ sub.pk }}" class="sr-only">ToUser</label>
                                                                    <input type="hidden" name="toUser" id="toUser{{ sub.pk }}" class="form-control" value="{{ sub.parentComment.user.pk }}">
                                                                </div>
                                                                <div class="col-md-12 col-sm-12 form-group">
                                                                    <input  type="submit" value="发送" class="btn btn-default pull-right">
                                                                </div>
                                                            </div>
                                                          </form>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                            {% empty %}
                                暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </div>
			</div>
		</div>
    {% endblock body %}

templates/blog/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    修改博客
{% endblock title %}
{% block narBlog %}
    fh5co-active
{% endblock narBlog %}
{% block body %}
    <div id="fh5co-main">
        <div class="fh5co-narrow-content">
            <form action="{% url 'blog:edit' post.pk %}" method="POST">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    <label for="title" class="sr-only">标题</label>
                    <input type="text" name="title" id="title" value="{{ post.title }}" placeholder="标题" class="form-control" maxlength="100" required>
                    {{ form.title.errors }}
                    {% if form.title.help_text %}
                        {{ form.title.help_text|safe }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="category" class="">目录：</label>
                    <select class="" id="category" name="category"  required>
                      {% for cate in categories %}
                          <option value="{{ cate.pk }}">{{ cate.name }}</option>
                      {% endfor %}
                    </select>
                    <label for="tag" class="">标签：</label>
                    <select class="" id="tag" name="tag" multiple required>
                      {% for tag in tags %}
                          <option value="{{ tag.pk }}">{{ tag.name }}</option>
                      {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="body" class="sr-only">内容</label>
                    <textarea  name="body" id="body" class=" form-control" cols="10" rows="20" required>{{ post.body }}</textarea>
                </div>
                <input type="hidden" value="{{ user.pk }}" name="author">
                <div class="form-group">
                    <button type="submit" class="btn btn-default form-control">确认修改</button>
                </div>
            </form>
        </div>
    </div>
{% endblock body %}

templates/blog/write.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    写博客
{% endblock title %}
{% block narBlog %}
    fh5co-active
{% endblock narBlog %}
{% block body %}
    <div id="fh5co-main">
        <div class="fh5co-narrow-content">
            <form action="{% url 'blog:write' %}" method="POST">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    <label for="title" class="sr-only">标题</label>
                    <input type="text" name="title" id="title" placeholder="标题" class="form-control" maxlength="100" required>
                    {{ form.title.errors }}
                    {% if form.title.help_text %}
                        {{ form.title.help_text|safe }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="category" class="">目录：</label>
                    <select class="" id="category" name="category" required>
                      {% for cate in categories %}
                          <option value="{{ cate.pk }}">{{ cate.name }}</option>
                      {% endfor %}
                    </select>
                    <label for="tag" class="">标签：</label>
                    <select class="" id="tag" name="tag" multiple required>
                      {% for tag in tags %}
                          <option value="{{ tag.pk }}">{{ tag.name }}</option>
                      {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="body" class="sr-only">内容</label>
                    <textarea  name="body" id="body" class=" form-control" cols="10" rows="20" required></textarea>
                </div>
                <input type="hidden" value="{{ user.pk }}" name="author">
                <div class="form-group">
                    <button type="submit" class="btn btn-default form-control">发表博客</button>
                </div>
            </form>
        </div>
    </div>
{% endblock body %}