MetaStudio/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('game.urls')),
    url(r'', include('comment.urls')),
    url(r'', include('account.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^api/', include('api.urls')),
]

account/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'account'

urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user/$',views.userInfo, name="userInfo"),
    url(r'^userInfo/$', views.infoChange, name='infoChange'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns=[
    url(r'test/$', views.Test.as_view(), name='Test'),
   
]

blog/urls.py
from django.conf.urls import url
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
from . import views
from MetaStudio.settings import MEDIA_ROOT

app_name = "blog"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index.html$', views.index, name='index'),
    url(r'^about.html$', views.about, name='about'),
    url(r'^blog.html$', views.blog, name='blog'),
    url(r'^contact.html$', views.contact, name='contact'),
    url(r'^post/(?P<pk>[0-9]+)', views.detail, name='detail'),
    url(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    url(r'^write/', views.write, name='write'),
    url(r'^post/delete/(?P<pk>[0-9]+)', views.delete, name='delete'),
    url(r'^post/edit/(?P<pk>[0-9]+)', views.edit, name='edit'),
    # url(r'^upload', views.uploadImage, name="UploadImage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'game'

urlpatterns=[
    url(r'^portfolio.html$', views.portfllio, name='portfolio'),
    url(r'^game/(?P<pk>[0-9]+)', views.gameInfo, name='gameInfo'),
    url(r'^download/Game/(?P<pk>[0-9]+)', views.downloadGame, name='downloadGame'),
    url(r'^upload/Game/$', views.uploadGame, name='uploadGame'),
    url(r'^delete/Game/(?P<pk>[0-9]+)', views.deleteGame, name='deleteGame'),
    url(r'^edit/Game/(?P<pk>[0-9]+)', views.editGame, name='editGame'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock title %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wang/css/wangEditor.min.css' %}">
	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>
    <div id="fh5co-page">
		<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
		<aside id="fh5co-aside" role="complementary" class="border js-fullheight">
			<h1 id="fh5co-logo"><a href="{% url 'blog:index' %}">Meta Studio</a></h1>
			<nav id="fh5co-main-menu" role="navigation">
				<ul>
					<li class="{% block narHome %}{% endblock narHome%}">
                        <a href="{% url 'blog:index' %}">首页</a>
                    </li>
                    <li class="{% block narGame %}{% endblock narGame%}">
                        <a href="{% url 'game:portfolio' %}">游戏</a>
                    </li>
					<li class="{% block narBlog %}{% endblock narBlog%}">
                        <a href="{% url 'blog:blog' %}">博客</a>
                    </li>
{#					<li class="{% block narAbout %}{% endblock narAbout%}">#}
{#                        <a href="{% url 'blog:about' %}">关于</a>#}
{#                    </li>#}
{#					<li class="{% block narContact %}{% endblock narContact%}">#}
{#                        <a href="{% url 'blog:contact' %}">联系</a>#}
{#                    </li>#}
                    <li class="{% block narLog %}{% endblock narLog%}">
                        {% if user.is_authenticated %}
                            <a href="{% url 'account:userInfo' %}">{{ user.username }}</a>
                        {% else %}
                            <a href="{% url 'login' %}">登陆/注册</a>
                        {% endif %}
                    </li>
				</ul>
			</nav>

			<div class="fh5co-footer">
				<p><small>&copy; 2016 Meta Studio. All Rights Reserved. </small></p>
			</div>
		</aside>

        {% block body %}
        {% endblock body %}
	</div>



	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>

    <script src="{% static 'wang/js/wangEditor.min.js' %}"></script>
	<!-- MAIN JS -->
	<script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/write.js' %}"></script>
	</body>
</html>